<a href="https://colab.research.google.com/github/Nikhilsimha31/climatescope-project/blob/feature%2Fdata-exploration/Climate_scope.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***ClimateScope:Visualizing Global Weather Trends and Extreme Events***
***
Project objective
The objective of ClimateScope is to analyze and visually represent global weather patterns using the Global Weather Repository dataset. This project aims to uncover seasonal trends, regional variations, and extreme weather events through interactive and insightful visualizations. By leveraging daily-updated, worldwide weather data, the project will enable users to explore climate behavior over time, compare conditions across regions, and identify anomalies. The ultimate goal is to provide an accessible, data-driven platform that supports climate awareness, decision-making, and further research into global weather dynamics.

In [1]:
#Download the Global Weather Repository dataset from Kaggle by using opendatasets
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from opendatasets) (4.67.1)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from opendatasets) (8.2.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2025.8.3)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.4.3)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->opendatasets) (0.5.1)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/nelgiriyewithana/global-weather-repository/data")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: Nikhilsimha123
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/nelgiriyewithana/global-weather-repository
Downloading global-weather-repository.zip to ./global-weather-repository

100%|██████████| 7.69M/7.69M [00:00<00:00, 807MB/s]

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/global-weather-repository/GlobalWeatherRepository.csv') #reading the file

***To view total observation and colums present in data set***

In [5]:
df.shape # to see total observation and colums present in data set

(97045, 41)

In [6]:
pd.set_option('display.max_columns', 41) # to see all columns

In [7]:
df.head() # to see top 5 row's

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.0,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.1,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.0,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.3,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.0,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [8]:
df.tail()# to see bottom 5 row's

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
97040,Venezuela,Caracas,10.5000,-66.9167,America/Caracas,1758960000,2025-09-27 04:00,26.2,79.2,Clear,4.0,6.5,180,S,1010.0,29.83,0.00,0.00,89,25,29.0,84.3,10.0,6.0,0.0,8.5,13.6,1557.70,65.0,25.900,6.475,22.200,22.385,2,2,06:16 AM,06:20 PM,10:46 AM,10:25 PM,Waxing Crescent,24
97041,Vietnam,Hanoi,21.0333,105.8500,Asia/Bangkok,1758959100,2025-09-27 14:45,34.2,93.6,Partly cloudy,4.0,6.5,322,NW,1010.0,29.83,0.65,0.03,56,50,45.2,113.4,10.0,6.0,6.6,5.1,8.3,1045.25,34.0,36.630,26.085,33.485,33.670,2,3,05:47 AM,05:48 PM,10:13 AM,09:07 PM,Waxing Crescent,21
97042,Yemen,Sanaa,15.3547,44.2067,Asia/Aden,1758959100,2025-09-27 10:45,23.3,74.0,Sunny,15.9,25.6,61,ENE,1015.0,29.96,0.00,0.00,20,0,22.8,73.0,10.0,6.0,8.4,18.3,29.4,299.70,77.0,1.850,4.625,27.935,81.585,2,3,05:53 AM,05:56 PM,10:16 AM,09:35 PM,Waxing Crescent,22
97043,Zambia,Lusaka,-15.4167,28.2833,Africa/Lusaka,1758959100,2025-09-27 09:45,23.4,74.2,Sunny,13.0,20.9,74,ENE,1018.0,30.05,0.00,0.00,45,7,24.8,76.6,10.0,6.0,3.9,14.9,24.0,358.90,81.0,1.295,1.110,17.575,17.945,2,2,05:53 AM,06:03 PM,09:18 AM,10:48 PM,Waxing Crescent,22
97044,Zimbabwe,Harare,-17.8178,31.0447,Africa/Harare,1758959100,2025-09-27 09:45,20.5,69.0,Sunny,8.1,13.0,68,ENE,1020.0,30.13,0.00,0.00,56,25,20.5,69.0,10.0,6.0,4.9,9.3,14.9,569.80,89.0,3.885,0.925,37.185,37.555,2,4,05:41 AM,05:53 PM,09:01 AM,10:42 PM,Waxing Crescent,22

In [9]:
df.info()#Inspect dataset structure, data types, and key variable

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97045 entries, 0 to 97044
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       97045 non-null  object
 1   location_name                 97045 non-null  object
 2   latitude                      97045 non-null  float64
 3   longitude                     97045 non-null  float64
 4   timezone                      97045 non-null  object
 5   last_updated_epoch            97045 non-null  int64
 6   last_updated                  97045 non-null  object
 7   temperature_celsius           97045 non-null  float64
 8   temperature_fahrenheit        97045 non-null  float64
 9   condition_text                97045 non-null  object
 10  wind_mph                      97045 non-null  float64
 11  wind_kph                      97045 non-null  float64
 12  wind_degree                   97045 non-null  int64
 13  wind_direction                97045 non-null  object
 14  pressure_mb                   97045 non-null  float64
 15  pressure_in                   97045 non-null  float64
 16  precip_mm                     97045 non-null  float64
 17  precip_in                     97045 non-null  float64
 18  humidity                      97045 non-null  int64
 19  cloud                         97045 non-null  int64
 20  feels_like_celsius            97045 non-null  float64
 21  feels_like_fahrenheit         97045 non-null  float64
 22  visibility_km                 97045 non-null  float64
 23  visibility_miles              97045 non-null  float64
 24  uv_index                      97045 non-null  float64
 25  gust_mph                      97045 non-null  float64
 26  gust_kph                      97045 non-null  float64
 27  air_quality_Carbon_Monoxide   97045 non-null  float64
 28  air_quality_Ozone             97045 non-null  float64
 29  air_quality_Nitrogen_dioxide  97045 non-null  float64
 30  air_quality_Sulphur_dioxide   97045 non-null  float64
 31  air_quality_PM2.5             97045 non-null  float64
 32  air_quality_PM10              97045 non-null  float64
 33  air_quality_us-epa-index      97045 non-null  int64
 34  air_quality_gb-defra-index    97045 non-null  int64
 35  sunrise                       97045 non-null  object
 36  sunset                        97045 non-null  object
 37  moonrise                      97045 non-null  object
 38  moonset                       97045 non-null  object
 39  moon_phase                    97045 non-null  object
 40  moon_illumination             97045 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 30.4+ MB